M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu20.04.1} date Sun 02 Oct 2022 03:02:44 AM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-02T03:02:44-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X67.75Y-39.5
T0
M30
